version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-connect:
    image: debezium/connect:2.7.3.Final
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "config-storage"
      OFFSET_STORAGE_TOPIC: "offset-storage"
      PLUGIN_PATH: "/kafka/connect"
    volumes:
      - connect_data:/kafka/connect
    depends_on:
      - kafka

  clickhouse:
    image: yandex/clickhouse-server:latest
    restart: always
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ''
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"  # Access the Kafka UI
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

  ksqldb:
    image: confluentinc/ksqldb-server:latest
    restart: always
    ports:
      - "8088:8088"  # Access the ksqlDB server
    environment:
      KSQL_CONFIG_DIR: /etc/ksql
      KSQL_HOST_NAME: ksqldb
      KSQL_BOOTSTRAP_SERVERS: "kafka:29092"
      KSQL_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"  # Ensure this points correctly to Kafka
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_ENABLE_AUTO_CREATE: "true"
    depends_on:
      - kafka

  # ksqlDB UI
  ksqldb-ui:
    image: deniskrumko/ksqldb-ui:latest
    ports:
      - 8081:8080
    environment:
      APP_CONFIG: /config.toml
    volumes:
      - ./development.toml:/config.toml

volumes:
  postgres_data:
  kafka_data:
  connect_data:
  clickhouse_data:
  ksql_data: